version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=wpaq
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=equipment_manager
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5440:5432